import { defineField, defineType } from 'sanity'

export const postType = defineType({
  name: 'post',
  title: 'Blog Post',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Meta Description',
      type: 'text',
      rows: 3,
      description: 'Used for SEO description and blog listing preview.',
    }),
    defineField({
      name: 'body',
      title: 'Body (HTML)',
      type: 'text',
      rows: 20,
      description: 'HTML content generated by Claude. Edit freely before publishing.',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      description: 'Leave blank to keep as draft. Set a date to publish.',
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'publishedAt' },
    prepare({ title, subtitle }) {
      return {
        title,
        subtitle: subtitle
          ? new Date(subtitle).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
          : 'Draft',
      }
    },
  },
})
